// src/game/ship/skills/registry/definitions/godhand.ts

import type { StarterShipSkillTree } from '@/game/ship/skills/interfaces/StarterShipSkillTree';

export const godhandSkillTree: StarterShipSkillTree = {
  shipId: 'Godhand Prototype',
  displayName: 'Godhand Prototype',
  gridSize: 12,
  maxSelectableNodes: 5,

  nodes: [
    {
      node: {
        id: 'laser-shield-pen',
        name: 'Phase Beam',
        description: 'Lasers penetrate shields',
        icon: 'icon-laser-penetrate',
        nodeSize: 'major',
        cost: 200,
        metadata: { laserShieldPenetration: true },
      },
      x: 4,
      y: 0,
      connectedTo: [],
    },
    {
      node: {
        id: 'laser-targeting',
        name: 'Autotarget Array',
        description: 'Lasers automatically track targets',
        icon: 'icon-laser-targeting',
        nodeSize: 'major',
        cost: 200,
        metadata: { laserTargeting: true },
      },
      x: 7,
      y: 0,
      connectedTo: ['laser-shield-pen'],
    },
    {
      node: {
        id: 'starter-left',
        name: 'Deployed Laser',
        description: 'Start with an extra laser block',
        icon: 'icon-laser-block',
        nodeSize: 'minor',
        cost: 100,
        metadata: { startingBlocks: ['laser1'] },
      },
      x: 4,
      y: 3,
      connectedTo: ['laser-shield-pen', 'laser-damage-left', 'laser-damage-right'],
    },
    {
      node: {
        id: 'starter-right',
        name: 'Deployed Laser',
        description: 'Start with an extra laser block',
        icon: 'icon-laser-block',
        nodeSize: 'minor',
        cost: 100,
        metadata: { startingBlocks: ['laser1'] },
      },
      x: 7,
      y: 3,
      connectedTo: ['laser-targeting', 'laser-damage-left', 'laser-damage-right'],
    },
    {
      node: {
        id: 'laser-damage-left',
        name: 'Refined Focus',
        description: '+2 laser damage',
        icon: 'icon-laser-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { laserDamage: 2 },
      },
      x: 3,
      y: 7,
      connectedTo: ['starter-left', 'starter-right'],
    },
    {
      node: {
        id: 'laser-damage-right',
        name: 'Refined Focus',
        description: '+2 laser damage',
        icon: 'icon-laser-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { laserDamage: 2 },
      },
      x: 8,
      y: 7,
      connectedTo: ['starter-left', 'starter-right'],
    },
    {
      node: {
        id: 'laser-width-1',
        name: 'Widened Beam',
        description: '+50 beam width',
        icon: 'icon-laser-width',
        nodeSize: 'minor',
        cost: 100,
        metadata: { laserBeamWidth: 50 },
      },
      x: 1,
      y: 9,
      connectedTo: ['laser-damage-left'],
    },
    {
      node: {
        id: 'laser-efficiency-1',
        name: 'Pulse Optimizer',
        description: '+20% laser efficiency',
        icon: 'icon-laser-efficiency',
        nodeSize: 'minor',
        cost: 100,
        metadata: { laserEfficiency: 0.2 },
      },
      x: 10,
      y: 9,
      connectedTo: ['laser-damage-right'],
    },
    {
      node: {
        id: 'laser-width-2',
        name: 'Widened Beam',
        description: '+50 beam width',
        icon: 'icon-laser-width',
        nodeSize: 'minor',
        cost: 100,
        metadata: { laserBeamWidth: 50 },
      },
      x: 4,
      y: 11,
      connectedTo: ['laser-width-1'],
      isStarter: true,
    },
    {
      node: {
        id: 'laser-efficiency-2',
        name: 'Pulse Optimizer',
        description: '+20% laser efficiency',
        icon: 'icon-laser-efficiency',
        nodeSize: 'minor',
        cost: 100,
        metadata: { laserEfficiency: 0.2 },
      },
      x: 7,
      y: 11,
      connectedTo: ['laser-efficiency-1'],
      isStarter: true,
    },
  ],
};
