// src/game/ship/skills/registry/definitions/halo.ts

import type { StarterShipSkillTree } from '@/game/ship/skills/interfaces/StarterShipSkillTree';

export const haloSkillTree: StarterShipSkillTree = {
  shipId: 'Halo Mk I',
  displayName: 'Halo Mk I',
  gridSize: 12,
  maxSelectableNodes: 5,

  nodes: [
    {
      node: {
        id: 'detonate-on-hit',
        name: 'Detonating Orbit',
        description: 'Halo blades explode on impact',
        icon: 'icon-blade-detonate',
        nodeSize: 'major',
        cost: 200,
        metadata: { haloBladeDetonateOnHit: true },
      },
      x: 5,
      y: 1,
      connectedTo: [],
    },
    {
      node: {
        id: 'damage-left',
        name: 'Reinforced Blades',
        description: '+5 halo blade damage',
        icon: 'icon-blade-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeDamage: 5 },
      },
      x: 3,
      y: 2,
      connectedTo: ['detonate-on-hit'],
    },
    {
      node: {
        id: 'damage-right',
        name: 'Reinforced Blades',
        description: '+5 halo blade damage',
        icon: 'icon-blade-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeDamage: 5 },
      },
      x: 7,
      y: 2,
      connectedTo: ['detonate-on-hit'],
    },
    {
      node: {
        id: 'freeze-on-hit',
        name: 'Cryogenic Blade',
        description: 'Freezes enemies on hit',
        icon: 'icon-blade-freeze',
        nodeSize: 'major',
        cost: 200,
        metadata: { haloBladeFreezeOnHit: true },
      },
      x: 1,
      y: 4,
      connectedTo: ['damage-left', 'size-up-1'],
    },
    {
      node: {
        id: 'damage-core',
        name: 'Reinforced Blades',
        description: '+5 halo blade damage',
        icon: 'icon-blade-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeDamage: 5 },
      },
      x: 5,
      y: 4,
      connectedTo: ['detonate-on-hit', 'damage-left', 'damage-right'],
    },
    {
      node: {
        id: 'split-blades',
        name: 'Fractured Orbit',
        description: 'Blades split into multiple projectiles',
        icon: 'icon-blade-split',
        nodeSize: 'major',
        cost: 200,
        metadata: { haloBladeSplitBlades: true },
      },
      x: 9,
      y: 4,
      connectedTo: ['damage-right', 'orbit-radius-1'],
    },
    {
      node: {
        id: 'size-up-1',
        name: 'Mammoth Blades',
        description: '+0.25 blade size',
        icon: 'icon-blade-size',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeSize: 0.25 },
      },
      x: 0,
      y: 6,
      connectedTo: ['freeze-on-hit'],
    },
    {
      node: {
        id: 'starter-left',
        name: 'Deployed Blade',
        description: 'Start with an extra halo blade',
        icon: 'icon-halo-block',
        nodeSize: 'minor',
        cost: 100,
        metadata: { startingBlocks: ['haloBlade1'] },
      },
      x: 3,
      y: 6,
      connectedTo: ['damage-core', 'freeze-on-hit', 'size-up-2'],
    },
    {
      node: {
        id: 'starter-right',
        name: 'Deployed Blade',
        description: 'Start with an extra halo blade',
        icon: 'icon-halo-block',
        nodeSize: 'minor',
        cost: 100,
        metadata: { startingBlocks: ['haloBlade1'] },
      },
      x: 7,
      y: 6,
      connectedTo: ['damage-core', 'split-blades', 'orbit-radius-2'],
    },
    {
      node: {
        id: 'orbit-radius-1',
        name: 'Orbital Extension',
        description: '+200 blade orbit radius',
        icon: 'icon-blade-radius',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeOrbitRadius: 200 },
      },
      x: 10,
      y: 6,
      connectedTo: ['split-blades'],
    },
    {
      node: {
        id: 'size-up-2',
        name: 'Mammoth Blades',
        description: '+0.25 blade size',
        icon: 'icon-blade-size',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeSize: 0.25 },
      },
      x: 1,
      y: 8,
      connectedTo: ['starter-left', 'size-up-1', 'size-up-3'],
    },
    {
      node: {
        id: 'damage-mid',
        name: 'Reinforced Blades',
        description: '+5 halo blade damage',
        icon: 'icon-blade-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeDamage: 5 },
      },
      x: 5,
      y: 8,
      connectedTo: ['starter-left', 'starter-right'],
    },
    {
      node: {
        id: 'orbit-radius-2',
        name: 'Orbital Extension',
        description: '+200 blade orbit radius',
        icon: 'icon-blade-radius',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeOrbitRadius: 200 },
      },
      x: 9,
      y: 8,
      connectedTo: ['starter-right', 'orbit-radius-1'],
    },
    {
      node: {
        id: 'size-up-3',
        name: 'Mammoth Blades',
        description: '+0.25 blade size',
        icon: 'icon-blade-size',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeSize: 0.25 },
      },
      x: 3,
      y: 10,
      connectedTo: ['size-up-2'],
    },
    {
      node: {
        id: 'orbit-radius-3',
        name: 'Orbital Extension',
        description: '+200 blade orbit radius',
        icon: 'icon-blade-radius',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeOrbitRadius: 200 },
      },
      x: 7,
      y: 10,
      connectedTo: ['orbit-radius-2'],
    },
    {
      node: {
        id: 'damage-terminal',
        name: 'Reinforced Blades',
        description: '+5 halo blade damage',
        icon: 'icon-blade-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { haloBladeDamage: 5 },
      },
      x: 5,
      y: 11,
      connectedTo: ['damage-mid', 'size-up-3', 'orbit-radius-3'],
      isStarter: true,
    },
  ],
};
