// src/game/ship/skills/registry/definitions/monarch.ts

import type { StarterShipSkillTree } from '@/game/ship/skills/interfaces/StarterShipSkillTree';

export const monarchSkillTree: StarterShipSkillTree = {
  shipId: 'Monarch',
  displayName: 'Monarch',
  gridSize: 12,
  maxSelectableNodes: 5,

  nodes: [
    {
      node: {
        id: 'grappling-lance',
        name: 'Grappling Lance',
        description: 'Explosive lances pull enemies',
        icon: 'icon-lance-grapple',
        nodeSize: 'major',
        cost: 300,
        metadata: { explosiveLanceGrappling: true },
        masteryRequirement: 5,
      },
      x: 5,
      y: 0,
      connectedTo: [],
    },
    {
      node: {
        id: 'starter-left',
        name: 'Deployed Lance',
        description: 'Start with an extra explosive lance block',
        icon: 'icon-extra-block',
        nodeSize: 'minor',
        cost: 200,
        metadata: { startingBlocks: ['explosiveLance1'] },
        masteryRequirement: 4,
      },
      x: 3,
      y: 2,
      connectedTo: ['grappling-lance'],
    },
    {
      node: {
        id: 'starter-right',
        name: 'Deployed Lance',
        description: 'Start with an extra explosive lance block',
        icon: 'icon-extra-block',
        nodeSize: 'minor',
        cost: 200,
        metadata: { startingBlocks: ['explosiveLance1'] },
        masteryRequirement: 4,
      },
      x: 7,
      y: 2,
      connectedTo: ['grappling-lance'],
    },
    {
      node: {
        id: 'starter-center',
        name: 'Deployed Lance',
        description: 'Start with an extra explosive lance block',
        icon: 'icon-extra-block',
        nodeSize: 'minor',
        cost: 200,
        metadata: { startingBlocks: ['explosiveLance1'] },
        masteryRequirement: 4,
      },
      x: 5,
      y: 3,
      connectedTo: ['grappling-lance', 'starter-left', 'starter-right', 'damage-left', 'damage-right'],
    },
    {
      node: {
        id: 'electrocution-lance',
        name: 'Electroshock Core',
        description: 'Lance detonations electrocute enemies',
        icon: 'icon-lance-electrocute',
        nodeSize: 'major',
        cost: 300,
        metadata: { explosiveLanceElectrocution: true },
        masteryRequirement: 5,
      },
      x: 0,
      y: 4,
      connectedTo: ['starter-left'],
    },
    {
      node: {
        id: 'lifesteal-lance',
        name: 'Vampiric Lance',
        description: 'Lance detonation restores health',
        icon: 'icon-lance-lifesteal',
        nodeSize: 'major',
        cost: 300,
        metadata: { explosiveLanceLifesteal: true },
        masteryRequirement: 5,
      },
      x: 10,
      y: 4,
      connectedTo: ['starter-right'],
    },
    {
      node: {
        id: 'damage-left',
        name: 'Amplified Charge',
        description: 'Explosive lance damage',
        icon: 'icon-lance-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { explosiveLanceDamage: 5 },
        masteryRequirement: 3,
      },
      x: 3,
      y: 5,
      connectedTo: ['starter-center', 'electrocution-lance'],
    },
    {
      node: {
        id: 'damage-right',
        name: 'Amplified Charge',
        description: 'Explosive lance damage',
        icon: 'icon-lance-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { explosiveLanceDamage: 5 },
        masteryRequirement: 3,
      },
      x: 7,
      y: 5,
      connectedTo: ['starter-center', 'lifesteal-lance'],
    },
    {
      node: {
        id: 'damage-center',
        name: 'Amplified Charge',
        description: 'Explosive lance damage',
        icon: 'icon-lance-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { explosiveLanceDamage: 5 },
        masteryRequirement: 3,
      },
      x: 5,
      y: 7,
      connectedTo: ['damage-left', 'damage-right', 'rate-boost-1', 'range-boost-1'],
    },
    {
      node: {
        id: 'rate-boost-1',
        name: 'Adaptive Coolant',
        description: 'Firing rate',
        icon: 'icon-lance-rate',
        nodeSize: 'minor',
        cost: 50,
        metadata: { explosiveLanceFiringRate: 0.08 },
        masteryRequirement: 2,
      },
      x: 3,
      y: 8,
      connectedTo: ['damage-left', 'damage-center'],
    },
    {
      node: {
        id: 'range-boost-1',
        name: 'Extended Lance',
        description: 'Lance range',
        icon: 'icon-lance-range',
        nodeSize: 'minor',
        cost: 50,
        metadata: { explosiveLanceRange: 300 },
        masteryRequirement: 2,
      },
      x: 7,
      y: 8,
      connectedTo: ['damage-right', 'damage-center'],
    },
    {
      node: {
        id: 'rate-boost-2',
        name: 'Adaptive Coolant',
        description: 'Firing rate',
        icon: 'icon-lance-rate',
        nodeSize: 'minor',
        cost: 25,
        metadata: { explosiveLanceFiringRate: 0.05 },
        masteryRequirement: 1,
      },
      x: 3,
      y: 11,
      connectedTo: ['rate-boost-1'],
      isStarter: true,
    },
    {
      node: {
        id: 'range-boost-2',
        name: 'Extended Lance',
        description: 'Lance range',
        icon: 'icon-lance-range',
        nodeSize: 'minor',
        cost: 25,
        metadata: { explosiveLanceRange: 200 },
        masteryRequirement: 1,
      },
      x: 7,
      y: 11,
      connectedTo: ['range-boost-1'],
      isStarter: true,
    },
  ],
};
