// src/game/ship/skills/registry/definitions/salamander.ts

import type { StarterShipSkillTree } from '@/game/ship/skills/interfaces/StarterShipSkillTree';

export const salamanderSkillTree: StarterShipSkillTree = {
  shipId: 'Salamander',
  displayName: 'Salamander',
  gridSize: 12,
  maxSelectableNodes: 5,

  nodes: [
    {
      node: {
        id: 'node-endless-ignition',
        name: 'Endless Ignition',
        description: 'Ignite duration is infinite.',
        icon: 'icon-explosion-fire',
        nodeSize: 'major',
        cost: 300,
        metadata: { endlessIgnition: true },
        masteryRequirement: 5,
      },
      x: 1,
      y: 2,
      connectedTo: ['size-node-1', 'starter-left'],
    },
    {
      node: {
        id: 'inner-flame',
        name: 'Inner Flame',
        description: 'Flames radiate outward from ship.',
        icon: 'icon-blade-detonate',
        nodeSize: 'major',
        cost: 300,
        metadata: { innerFlame: true },
        masteryRequirement: 5,
      },
      x: 9,
      y: 2,
      connectedTo: ['crit-node-1', 'starter-right'],
    },
    {
      node: {
        id: 'size-node-1',
        name: 'Growing Flames',
        description: 'Maximizes flame size.',
        icon: 'icon-blade-size',
        nodeSize: 'minor',
        cost: 100,
        metadata: { flameThrowerSize: 0.75 },
        masteryRequirement: 3,
      },
      x: 0,
      y: 6,
      connectedTo: ['node-endless-ignition', 'size-node-2', 'starter-left'],
    },
    {
      node: {
        id: 'crit-node-1',
        name: 'Infernal Precision',
        description: 'Great chance to deal extra damage.',
        icon: 'icon-critical-hit',
        nodeSize: 'minor',
        cost: 100,
        metadata: { flameThrowerCriticalChance: 0.1 },
        masteryRequirement: 3,
      },
      x: 10,
      y: 6,
      connectedTo: ['inner-flame', 'crit-node-2', 'starter-right'],
    },
    {
      node: {
        id: 'starter-left',
        name: 'Deployed Flames',
        description: 'Start with an extra flame thrower block.',
        icon: 'icon-extra-block',
        nodeSize: 'minor',
        cost: 200,
        metadata: { startingBlocks: ['flameThrower1'] },
        masteryRequirement: 4,
      },
      x: 3,
      y: 7,
      connectedTo: [
        'node-endless-ignition',
        'size-node-1',
        'size-node-2',
        'starter-right',
      ],
    },
    {
      node: {
        id: 'starter-right',
        name: 'Deployed Flames',
        description: 'Start with an extra flame thrower block.',
        icon: 'icon-extra-block',
        nodeSize: 'minor',
        cost: 200,
        metadata: { startingBlocks: ['flameThrower1'] },
        masteryRequirement: 4,
      },
      x: 7,
      y: 7,
      connectedTo: [
        'inner-flame',
        'crit-node-1',
        'crit-node-2',
        'starter-left',
      ],
    },
    {
      node: {
        id: 'size-node-2',
        name: 'Growing Flames',
        description: 'Further increases flame size.',
        icon: 'icon-blade-size',
        nodeSize: 'minor',
        cost: 50,
        metadata: { flameThrowerSize: 0.6 },
        masteryRequirement: 2,
      },
      x: 1,
      y: 9,
      connectedTo: ['size-node-3', 'size-node-1', 'starter-left'],
    },
    {
      node: {
        id: 'crit-node-2',
        name: 'Infernal Precision',
        description: 'Chance to deal even more extra damage.',
        icon: 'icon-critical-hit',
        nodeSize: 'minor',
        cost: 50,
        metadata: { flameThrowerCriticalChance: 0.08 },
        masteryRequirement: 2,
      },
      x: 9,
      y: 9,
      connectedTo: ['crit-node-3', 'crit-node-1', 'starter-right'],
    },
    {
      node: {
        id: 'size-node-3',
        name: 'Growing Flames',
        description: 'Increases size of flames.',
        icon: 'icon-blade-size',
        nodeSize: 'minor',
        cost: 25,
        metadata: { flameThrowerSize: 0.4 },
        masteryRequirement: 1,
      },
      x: 4,
      y: 10,
      connectedTo: ['size-node-2', 'crit-node-3'],
      isStarter: true,
    },
    {
      node: {
        id: 'crit-node-3',
        name: 'Infernal Precision',
        description: 'Chance to deal extra damage.',
        icon: 'icon-critical-hit',
        nodeSize: 'minor',
        cost: 25,
        metadata: { flameThrowerCriticalChance: 0.05 },
        masteryRequirement: 1,
      },
      x: 6,
      y: 10,
      connectedTo: ['crit-node-2', 'size-node-3'],
      isStarter: true,
    },
  ],
};
