// src/game/ship/skills/registry/definitions/sv1.ts

import type { StarterShipSkillTree } from '@/game/ship/skills/interfaces/StarterShipSkillTree';

export const sw1SkillTree: StarterShipSkillTree = {
  shipId: 'SW-1 Standard Issue',
  displayName: 'SW-1 Standard Issue',
  gridSize: 12,
  maxSelectableNodes: 5,

  nodes: [
    {
      node: {
        id: 'damage-core',
        name: 'Core Damage',
        description: '+10 turret damage',
        icon: 'icon-core-damage',
        nodeSize: 'major',
        cost: 500,
        metadata: { turretDamage: 10 },
        masteryRequirement: 5,
      },
      x: 5,
      y: 1,
      connectedTo: [],
    },
    {
      node: {
        id: 'splitshot-matrix',
        name: 'Splitshot Matrix',
        description: 'Turrets fire splitting shots',
        icon: 'icon-splitshot-matrix',
        nodeSize: 'major',
        cost: 200,
        metadata: { turretSplitShots: true },
        masteryRequirement: 5,
      },
      x: 1,
      y: 3,
      connectedTo: [],
    },
    {
      node: {
        id: 'penetrating-ammo',
        name: 'Penetrating Ammo',
        description: 'Turret shots pierce enemies',
        icon: 'icon-penetrating-ammo',
        nodeSize: 'major',
        cost: 500,
        metadata: { turretPenetratingShots: true },
        masteryRequirement: 5,
      },
      x: 9,
      y: 3,
      connectedTo: [],
    },
    {
      node: {
        id: 'damage-node-2',
        name: 'Refined Rounds',
        description: '+5 turret damage',
        icon: 'icon-damage-boost',
        nodeSize: 'minor',
        cost: 400,
        metadata: { turretDamage: 5 },
        masteryRequirement: 4,
      },
      x: 5,
      y: 4,
      connectedTo: ['damage-core'],
    },
    {
      node: {
        id: 'crit-node-1',
        name: 'Targeting Subroutine',
        description: 'Chance to deal extra damage',
        icon: 'icon-critical-hit',
        nodeSize: 'minor',
        cost: 400,
        metadata: { turretCriticalChance: 0.07 },
        masteryRequirement: 4,
      },
      x: 3,
      y: 5,
      connectedTo: ['splitshot-matrix'],
    },
    {
      node: {
        id: 'proj-speed-1',
        name: 'Kinetic Thrusters',
        description: 'Projectiles go vroom!',
        icon: 'icon-projectile-speed',
        nodeSize: 'minor',
        cost: 400,
        metadata: { turretProjectileSpeed: 200 },
        masteryRequirement: 4,
      },
      x: 7,
      y: 5,
      connectedTo: ['penetrating-ammo'],
    },
    {
      node: {
        id: 'starter-center',
        name: 'Deployed Turret',
        description: 'Start with an extra turret block',
        icon: 'icon-extra-block',
        nodeSize: 'minor',
        cost: 300,
        metadata: { startingBlocks: ['turret1'] },
        masteryRequirement: 3,
      },
      x: 5,
      y: 7,
      connectedTo: ['crit-node-1', 'damage-node-2', 'proj-speed-1'],
    },
    {
      node: {
        id: 'crit-node-2',
        name: 'Surgical Precision',
        description: 'Chance to deal extra damage',
        icon: 'icon-critical-hit',
        nodeSize: 'minor',
        cost: 200,
        metadata: { turretCriticalChance: 0.05 },
        masteryRequirement: 2,
      },
      x: 3,
      y: 9,
      connectedTo: ['starter-center'],
    },
    {
      node: {
        id: 'proj-speed-2',
        name: 'Hypercharged Rounds',
        description: 'Projectiles go vroom!',
        icon: 'icon-projectile-speed',
        nodeSize: 'minor',
        cost: 200,
        metadata: { turretProjectileSpeed: 100 },
        masteryRequirement: 2,
      },
      x: 7,
      y: 9,
      connectedTo: ['starter-center'],
    },
    {
      node: {
        id: 'crit-node-3',
        name: 'Surgical Precision',
        description: 'Chance to deal extra damage',
        icon: 'icon-critical-hit',
        nodeSize: 'minor',
        cost: 100,
        metadata: { turretCriticalChance: 0.05 },
        masteryRequirement: 1,
      },
      x: 1,
      y: 11,
      connectedTo: ['crit-node-2'],
      isStarter: true,
    },
    {
      node: {
        id: 'proj-speed-3',
        name: 'Hypercharged Rounds',
        description: 'Projectiles go vroom!',
        icon: 'icon-projectile-speed',
        nodeSize: 'minor',
        cost: 100,
        metadata: { turretProjectileSpeed: 100 },
        masteryRequirement: 1,
      },
      x: 9,
      y: 11,
      connectedTo: ['proj-speed-2'],
      isStarter: true,
    },
  ],
};
