// src/game/ship/skills/registry/definitions/vanguard.ts

import type { StarterShipSkillTree } from '@/game/ship/skills/interfaces/StarterShipSkillTree';

export const vanguardSkillTree: StarterShipSkillTree = {
  shipId: 'Vanguard',
  displayName: 'Vanguard',
  gridSize: 12,
  maxSelectableNodes: 5,

  nodes: [
    {
      node: {
        id: 'ignite-explosion',
        name: 'Volatile Payload',
        description: 'Seeker missile explosions ignite enemies',
        icon: 'icon-explosion-fire',
        nodeSize: 'major',
        cost: 200,
        metadata: { igniteOnSeekerMissileExplosion: true },
      },
      x: 0,
      y: 3,
      connectedTo: [],
    },
    {
      node: {
        id: 'seeker-double-radius',
        name: 'Overloaded Warheads',
        description: '+1 explosion radius, 10% double shot chance',
        icon: 'icon-double-radius',
        nodeSize: 'major',
        cost: 200,
        metadata: {
          seekerMissileExplosionRadius: 2,
          doubleSeekerMissileShotChance: 0.1,
        },
      },
      x: 5,
      y: 3,
      connectedTo: [],
    },
    {
      node: {
        id: 'freeze-explosion',
        name: 'Cryo Detonation',
        description: 'Seeker missile explosions freeze time',
        icon: 'icon-time-freeze',
        nodeSize: 'major',
        cost: 200,
        metadata: { timeFreezeOnSeekerMissileExplosion: true },
      },
      x: 10,
      y: 3,
      connectedTo: [],
    },
    {
      node: {
        id: 'starter-left',
        name: 'Deployed Seeker',
        description: 'Start with an extra seeker missile block',
        icon: 'icon-seeker-block',
        nodeSize: 'minor',
        cost: 100,
        metadata: { startingBlocks: ['heatSeeker1'] },
      },
      x: 2,
      y: 5,
      connectedTo: ['ignite-explosion', 'seeker-double-radius', 'damage-left'],
    },
    {
      node: {
        id: 'starter-right',
        name: 'Deployed Seeker',
        description: 'Start with an extra seeker missile block',
        icon: 'icon-seeker-block',
        nodeSize: 'minor',
        cost: 100,
        metadata: { startingBlocks: ['heatSeeker1'] },
      },
      x: 8,
      y: 5,
      connectedTo: ['freeze-explosion', 'seeker-double-radius', 'damage-right'],
    },
    {
      node: {
        id: 'damage-left',
        name: 'Payload Upgrade',
        description: '+5 seeker missile damage',
        icon: 'icon-missile-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { seekerMissileDamage: 5 },
      },
      x: 0,
      y: 7,
      connectedTo: ['starter-left'],
    },
    {
      node: {
        id: 'damage-center',
        name: 'Payload Upgrade',
        description: '+5 seeker missile damage',
        icon: 'icon-missile-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { seekerMissileDamage: 5 },
      },
      x: 5,
      y: 7,
      connectedTo: ['starter-left', 'starter-right', 'double-shot-1', 'radius-1'],
    },
    {
      node: {
        id: 'damage-right',
        name: 'Payload Upgrade',
        description: '+5 seeker missile damage',
        icon: 'icon-missile-damage',
        nodeSize: 'minor',
        cost: 100,
        metadata: { seekerMissileDamage: 5 },
      },
      x: 10,
      y: 7,
      connectedTo: ['starter-right'],
    },
    {
      node: {
        id: 'double-shot-1',
        name: 'Rapid Launch',
        description: '+5% chance to double shot',
        icon: 'icon-double-shot',
        nodeSize: 'minor',
        cost: 100,
        metadata: { doubleSeekerMissileShotChance: 0.05 },
      },
      x: 2,
      y: 9,
      connectedTo: ['damage-left', 'damage-center'],
    },
    {
      node: {
        id: 'radius-1',
        name: 'Blast Radius',
        description: '+1 seeker explosion radius',
        icon: 'icon-blast-radius',
        nodeSize: 'minor',
        cost: 100,
        metadata: { seekerMissileExplosionRadius: 1 },
      },
      x: 8,
      y: 9,
      connectedTo: ['damage-right', 'damage-center'],
    },
    {
      node: {
        id: 'double-shot-2',
        name: 'Rapid Launch',
        description: '+5% chance to double shot',
        icon: 'icon-double-shot',
        nodeSize: 'minor',
        cost: 100,
        metadata: { doubleSeekerMissileShotChance: 0.05 },
      },
      x: 4,
      y: 11,
      connectedTo: ['double-shot-1'],
      isStarter: true,
    },
    {
      node: {
        id: 'radius-2',
        name: 'Blast Radius',
        description: '+1 seeker explosion radius',
        icon: 'icon-blast-radius',
        nodeSize: 'minor',
        cost: 100,
        metadata: { seekerMissileExplosionRadius: 1 },
      },
      x: 6,
      y: 11,
      connectedTo: ['radius-1'],
      isStarter: true,
    },
  ],
};
